version: "3"
services:

  php:
    build: ./docker/php
    container_name: "laravel-php"
    volumes:
      - ./src:/usr/share/nginx/html

  mysql:
    image: mysql:8.0
    container_name: "laravel-mysql"
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      TZ: "Asia/Tokyo"

  nginx:
    image: nginx:1.21.5
    container_name: laravel-nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - php